env:
  es2021: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
  - prettier
plugins:
  - jest
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: 
  no-await-in-loop: 0
  no-empty: 0
  no-shadow: 0
  class-methods-use-this: 0
  no-restricted-syntax: 0

